# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: 'MAVERIK'
  demands:
   - Agent.Name -equals slazerdevops01

variables:
  javaHome: '/opt/cicd-tools/' # Specify the desired installation

steps:
- task: UseJavaVersion@0
  inputs:
    versionSpec: '11' # Use the desired Java version
    addToPath: false  # Do not automatically add Java to the PATH

- script: |
    echo "##vso[task.setvariable variable=JAVA_HOME]$JAVA_HOME"
    echo "##vso[task.prependpath]$JAVA_HOME/bin"
  displayName: 'Set JAVA_HOME and add to PATH'

- task: MavenInstaller@1
  inputs:
    mavenVersionOption: 'Path'
    mavenDownloadPath: '/opt/cicd-tools/' # Specify the desired installation path
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
